In [1]:
# Connecting drive contents to the colab
from google.colab import drive
drive.mount('/content/drive')

ModuleNotFoundError: No module named 'google.colab'

In [ ]:
import os
os.chdir("/content/drive/MyDrive/PhD/Intern projects/NandhaKishore - Multi-dimensional co-occurrence network")

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot

Original_data_frame=pd.read_csv('DIABIMMUNE_WGS.WGS.taxon_abundance.tsv', sep='\t')

df=Original_data_frame.copy()

In [ ]:
df.head()

In [ ]:
df.info()

In [ ]:
df.columns

In [ ]:
df['Unnamed: 0']

In [ ]:
# Correcting Typo errors in the name of the micro organism

df.at[14, 'Unnamed: 0']='Bacteria;Actinobacteria;Actinobacteria;Actinomycetales;Actinomycetaceae;Actinomyces;Actinomyces sp.oral_taxon_181'
df.at[188, 'Unnamed: 0']='Bacteria;Firmicutes;Bacilli;Lactobacillales;Enterococcaceae;Enterococcus;Enterococcus sp.RIT_PI_f'
df.at[472, 'Unnamed: 0']='Bacteria;Firmicutes;Negativicutes;Selenomonadales;Selenomonadaceae;Selenomonas;Selenomonas sp.oral_taxon_892'
df.at[586, 'Unnamed: 0']='Bacteria;Proteobacteria;Gammaproteobacteria;Pasteurellales;Pasteurellaceae;Aggregatibacter;Aggregatibacter sp.oral_taxon_458'

In [ ]:
# Splitting the columns and stored it in separate dataframe and can take the desired column
df_col = df['Unnamed: 0'].str.split(';', n=6, expand =True)

In [ ]:
taxa_df["Kingdom"] = pd.DataFrame(df_col[0])
taxa_df["Phylum"] = df_col[1]
taxa_df["Phylum"] = df_col[1]
taxa_df["Class"] = df_col[2]
taxa_df["Order"] = df_col[3]
taxa_df["Family"] = df_col[4]
taxa_df["Genus"] = df_col[5]
taxa_df["Species"]=df_col[6]
taxa_df.head()

In [ ]:
#extracting Species Name
df['SpeciesName']= df['Unnamed: 0'].apply(lambda x: str(x).replace(';', ', '))

df['SpeciesName']=df['SpeciesName'].str.split().str[-2:]

species=df['SpeciesName']
df=df.drop(columns=['SpeciesName'])

df.insert(1,'Species',species)

In [ ]:
#extracting Genus Name
df['GenusName']= df['Unnamed: 0'].apply(lambda x: str(x).replace(';', ', '))

df['GenusName']=df['GenusName'].str.split().str[-3:-2]
df['GenusName']=df['GenusName'].apply(lambda x: str(x).replace(',',''))

genus=df['GenusName']
df=df.drop(columns=['GenusName'])

df.insert(1,'Genus',genus)

In [ ]:
# Cleaning the unnecessary punctutaions in the name of the micro organism 
df['Genus']=df['Genus'].apply(lambda x: str(x).replace('\'',''))
df['Species']=df['Species'].apply(lambda x: str(x).replace(',',''))
df['Species']=df['Species'].apply(lambda x: str(x).replace('\'',''))

In [ ]:
new_df = df.copy()

# Adding Genus & Species to the dataframe
new_df.insert(0,'Species',taxa_df['Species'])
new_df.insert(0,'Genus',taxa_df['Genus'])
new_df.head()

,Genus,Species,Unnamed: 0,3120848,3120844,3120810,3120666,3120559,3120543,3120536,...,3000110,3000106,3000095,3000085,3000064,3000058,3000054,3000052,3000044,3000007
0,Methanobrevibacter,Methanobrevibacter smithii,Archaea;Euryarchaeota;Methanobacteria;Methanob...,NaN,0.24428,NaN,1.95881,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Methanobrevibacter,Methanobrevibacter woesei,Archaea;Euryarchaeota;Methanobacteria;Methanob...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Actinobaculum,Actinobaculum massiliense,Bacteria;Actinobacteria;Actinobacteria;Actinom...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Actinomyces,Actinomyces europaeus,Bacteria;Actinobacteria;Actinobacteria;Actinom...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Actinomyces,Actinomyces graevenitzii,Bacteria;Actinobacteria;Actinobacteria;Actinom...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
new_df.to_csv('newDF.csv')

In [ ]:
#Database with correct genus and species names 
new_df

,Unnamed: 0,Genus,Species,3120848,3120844,3120810,3120666,3120559,3120543,3120536,...,3000110,3000106,3000095,3000085,3000064,3000058,3000054,3000052,3000044,3000007
0,Archaea;Euryarchaeota;Methanobacteria;Methanob...,[Methanobrevibacter],[Methanobrevibacter smithii],NaN,0.24428,NaN,1.95881,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Archaea;Euryarchaeota;Methanobacteria;Methanob...,[Methanobrevibacter],[Methanobrevibacter woesei],NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Bacteria;Actinobacteria;Actinobacteria;Actinom...,[Actinobaculum],[Actinobaculum massiliense],NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Bacteria;Actinobacteria;Actinobacteria;Actinom...,[Actinomyces],[Actinomyces europaeus],NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Bacteria;Actinobacteria;Actinobacteria;Actinom...,[Actinomyces],[Actinomyces graevenitzii],NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,Bacteria;Synergistetes;Synergistia;Synergistal...,[Pyramidobacter],[Pyramidobacter piscolens],NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
610,Bacteria;Verrucomicrobia;Verrucomicrobiae;Verr...,[Akkermansia],[Akkermansia muciniphila],0.01543,8.59480,NaN,1.41401,2.22417,0.06219,0.32564,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
611,Eukaryota;Ascomycota;Saccharomycetes;Saccharom...,[Candida],[Candida albicans],NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
612,Eukaryota;Ascomycota;Saccharomycetes;Saccharom...,[Candida],[Candida parapsilosis],NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
613,Eukaryota;Eukaryota_unclassified;Eukaryota_unc...,[Blastocystis],[sp. subtype_1],NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
#replaceing NaN with mean of their columns 
values_df=new_df.drop(columns=['Unnamed: 0','Genus','Species'], axis=1)

In [ ]:
values_df

In [ ]:
values_df.isnull().values.any()
values_df.isnull().sum()

Here, NaN represents either absence of the micro-organisms due to technical or biological problem. So we can't impute the NaNs using mean. We can replace the NaN with **zero**.

In [ ]:
values_df=values_df.fillna(0)

In [ ]:
values_df

In [ ]:
values_df.isnull().values.any()
#values_df.isnull().sum()

False

In [ ]:
Naming_df=new_df[['Unnamed: 0','Genus','Species']]
Naming_df

,Unnamed: 0,Genus,Species
0,Archaea;Euryarchaeota;Methanobacteria;Methanob...,Methanobrevibacter,Methanobrevibacter smithii
1,Archaea;Euryarchaeota;Methanobacteria;Methanob...,Methanobrevibacter,Methanobrevibacter woesei
2,Bacteria;Actinobacteria;Actinobacteria;Actinom...,Actinobaculum,Actinobaculum massiliense
3,Bacteria;Actinobacteria;Actinobacteria;Actinom...,Actinomyces,Actinomyces europaeus
4,Bacteria;Actinobacteria;Actinobacteria;Actinom...,Actinomyces,Actinomyces graevenitzii
...,...,...,...
609,Bacteria;Synergistetes;Synergistia;Synergistal...,Pyramidobacter,Pyramidobacter piscolens
610,Bacteria;Verrucomicrobia;Verrucomicrobiae;Verr...,Akkermansia,Akkermansia muciniphila
611,Eukaryota;Ascomycota;Saccharomycetes;Saccharom...,Candida,Candida albicans
612,Eukaryota;Ascomycota;Saccharomycetes;Saccharom...,Candida,Candida parapsilosis
613,Eukaryota;Eukaryota_unclassified;Eukaryota_unc...,Blastocystis,Blastocystis sp. subtype_1

In [ ]:
#Final Databse with proper naming and values 
final_df=pd.concat([Naming_df, values_df], axis=1, join='inner')
final_df

,Unnamed: 0,Genus,Species,3120848,3120844,3120810,3120666,3120559,3120543,3120536,...,3000110,3000106,3000095,3000085,3000064,3000058,3000054,3000052,3000044,3000007
0,Archaea;Euryarchaeota;Methanobacteria;Methanob...,Methanobrevibacter,Methanobrevibacter smithii,0.00000,0.24428,0.0,1.95881,0.00000,0.00000,0.00000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,Archaea;Euryarchaeota;Methanobacteria;Methanob...,Methanobrevibacter,Methanobrevibacter woesei,0.00000,0.00000,0.0,0.00000,0.00000,0.00000,0.00000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,Bacteria;Actinobacteria;Actinobacteria;Actinom...,Actinobaculum,Actinobaculum massiliense,0.00000,0.00000,0.0,0.00000,0.00000,0.00000,0.00000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,Bacteria;Actinobacteria;Actinobacteria;Actinom...,Actinomyces,Actinomyces europaeus,0.00000,0.00000,0.0,0.00000,0.00000,0.00000,0.00000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Bacteria;Actinobacteria;Actinobacteria;Actinom...,Actinomyces,Actinomyces graevenitzii,0.00000,0.00000,0.0,0.00000,0.00000,0.00000,0.00000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,Bacteria;Synergistetes;Synergistia;Synergistal...,Pyramidobacter,Pyramidobacter piscolens,0.00000,0.00000,0.0,0.00000,0.00000,0.00000,0.00000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
610,Bacteria;Verrucomicrobia;Verrucomicrobiae;Verr...,Akkermansia,Akkermansia muciniphila,0.01543,8.59480,0.0,1.41401,2.22417,0.06219,0.32564,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
611,Eukaryota;Ascomycota;Saccharomycetes;Saccharom...,Candida,Candida albicans,0.00000,0.00000,0.0,0.00000,0.00000,0.00000,0.00000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
612,Eukaryota;Ascomycota;Saccharomycetes;Saccharom...,Candida,Candida parapsilosis,0.00000,0.00000,0.0,0.00000,0.00000,0.00000,0.00000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
613,Eukaryota;Eukaryota_unclassified;Eukaryota_unc...,Blastocystis,Blastocystis sp. subtype_1,0.00000,0.00000,0.0,0.00000,0.00000,0.00000,0.00000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0